---
namespace: "cyberark"
name: "conjur"
version: "1.3.8"
readme: README.md
authors:
  - CyberArk Business Development (@cyberark-bizdev)
  - (@cyberark/community-and-integrations-team)
description: "This is a Collection of the CyberArk Secrets Manager toolkit."
license: ["Apache-2.0"]
tags:
  - cyberark
  - conjur
  - access
  - security
  - account
  - vault
  - identity
  - credential
  - secret
  - privileged
  - devops
repository: "https://github.com/cyberark/ansible-conjur-collection"
issues: "https://github.com/cyberark/ansible-conjur-collection/issues"
build_ignore:
  - "dev"
  - "ci"
  - "secrets.yml"
  - ".infrapool"
  - ".infrapool@tmp"
  - "conjur-cloud-tools"
  - "internal_url_patterns"
  - ".codeclimate.yml"
  - ".github"
  - ".gitmodules"
  - "Jenkinsfile"
  - "kics.config"
  - ".ansible"
