namespace: "cyberark"
name: "conjur"
version: "1.0.7"
readme: README.md
authors:
    - CyberArk Business Development (@cyberark-bizdev)
    - CyberArk Community and Integrations Team (@cyberark/community-and-integrations-team)
description: "This is a Collection of the CyberArk Conjur/DAP toolkit."
license: "Apache-2.0"
tags:
  - cyberark
  - conjur
  - access
  - security
  - account
  - vault
  - identity
  - credential
  - secret
  - privileged
  - devops
repository: "https://github.com/cyberark/ansible-conjur-collection"
