FROM nginx:1.28.0-alpine3.21-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apk update && \
    apk add --no-cache iputils procps openssl && \
    rm -rf /var/cache/apk/*

WORKDIR /etc/nginx/

COPY proxy/ssl.conf /etc/ssl/openssl.cnf

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -config /etc/ssl/openssl.cnf -extensions v3_ca \
    -keyout cert.key -out cert.crt

COPY proxy/default.conf /etc/nginx/conf.d/default.conf
