---
- name: Generate Host Factory Token
  shell: |
    docker exec conjur_client \
      conjur hostfactory tokens create --duration-days 1 --cidr 172.17.0.0/16 host-identity
  register: hostfactory_output
  no_log: yes

- name: Return Only API Key
  shell: echo '{{ hostfactory_output.stdout_lines[2] }}' | awk '/"token":/{print $2}' | tr -d '"' | tr -d '\r\n'
  register: hostfactory_token
  no_log: yes