# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vbguest.auto_update = false
  config.vm.synced_folder  ".", "/vagrant", disabled: false
  config.vm.provision "shell", path: "docker.sh", privileged: false
  config.vm.provision "shell", path: "provision.sh", privileged: false
  config.vm.provision :reload
  config.vm.provision "ansible_local", playbook: "conjur.yml"
end
